packages:
  - "apps/*"
  - "libs/utils"
  - "libs/types"
  - "libs/materials/*"

catalog:
  typescript: 5.9.2
  ts-node: 10.9.2
  ts-node-dev: 2.0.0
  cross-env: ^7.0.3
  globals: 16.5.0
  prettier: 3.6.2
  less: 4.4.2
  "@monaco-editor/react": 4.7.0

catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
    react-router-dom: 6.30.2
  chamn:
    "@chamn/engine": 0.9.3
    "@chamn/model": 0.9.3
    "@chamn/render": 0.9.3
    "@chamn/material": 0.9.3
  antd:
    antd: 5.15.2
    "@ant-design/icons": 5.3.1
  eslint:
    eslint: 9.39.1
    eslint-plugin-react-hooks: 5.2.0
    eslint-plugin-react-refresh: 0.4.24
    eslint-plugin-prettier: 5.5.4
    eslint-config-prettier: 10.1.8
    typescript-eslint: 8.46.3
    "@eslint/js": 9.39.1
  vite:
    vite: 7.2.2
    "@vitejs/plugin-react": 5.1.0
    vite-plugin-monaco-editor: 1.1.0
    vite-plugin-dts: 4.5.4
  typings:
    "@types/react": 18.2.0
    "@types/react-dom": 18.2.0
    "@types/node": 24.10.1
